github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addLabel: prebuilt-in-gitpod
vscode:
  extensions:
    - hbenl.vscode-test-explorer
    - Swellaby.vscode-rust-test-adapter
    - serayuzgur.crates
    - belfz.search-crates-io
    - bungcip.better-toml
    - webfreak.debug
    - matklad.rust-analyzer
