[package]
name = "guessing_game"
version = "1.0.0"
authors = ["Sergey Maslakov <s.a.maslakov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"