[package]
name = "converter"
version = "0.1.0"
authors = ["Sergey Maslakov <s.a.maslakov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
